### ISSUE TITLE
Error "registry refers to a nonexistent Java Runtime Environment"

### ISSUE THREAD

**Issue by cork2win** [soichih/dsbudget#80]
Tried to run dsbudget.exe this morning and receive this error "The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted.  The system cannot find the file specified."

At cmd prompt java -version produces "java version 1.8.0_101 Runtime Environment build 1.8.0_101-b13".

I'm guessing my machine updated Java recently, I can't really remember.  Will dsbudget work on this Java version or do I need to roll back?

**Comment by soichih** [comment]
I should work with Java 1.8. Can you try re-installing Java manually?

https://java.com/en/download/

**Comment by cork2win** [comment]
That solved it, thank you so much!  Love your software.  :)
